name: doctor_apk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences:
  pinput: ^5.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.2.2
  image_picker:
  connectivity_plus: ^2.3.1
  photo_view:
  url_launcher:
  flutter_widget_from_html: ^0.9.0+2
  agora_rtc_engine: ^6.2.4
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true
  fonts:
    - family: poppins_reg
      fonts:
        - asset: assets/font/poppins_regular.ttf

    - family: prosto_one_regular
      fonts:
        - asset: assets/font/prosto_one_regular.ttf

  assets:
    #    - lib/model/
    #    - lib/repo/
    #    - lib/res/
    #    - lib/view/
    #    - lib/view/home/
    #    - lib/view/home/widgets/
    #    - lib/view_model/
    - assets/img/
    - assets/icon/
    - assets/bgimg/
    - assets/
    - assets/font/

